[build]
builder = "NIXPACKS"
buildCommand = "./gradlew clean bootJar -x test"

[deploy]
startCommand = "java -Xmx400m -XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0 -jar build/libs/app.jar --spring.profiles.active=railway"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
